pipeline {
    agent any

     tools {nodejs "node"}

stages {
    stage('prepare') {
        steps {
            dir('frontend'){
                sh 'npm install'
               
            }
        }
    }
    stage('build') {
        steps {
            dir('frontend'){
                sh 'npm run build'

                sh '''
                echo 'Dockerimage build'
                docker build -t docker-reactnative:0.0.1 .
                '''
            }
        }
    }
    stage('Deploy') {
        steps {
            dir('frontend'){
                sh '''
                echo 'Deploy'
                docker stop puppyfront
                docker rm puppyfront
                docker run -d -p 3000:3000 --name puppyfront docker-reactnative:0.0.1
                '''
            }
        }
    }
}
}